// Static 5-item preview shown on the Home page before the catalog.preview
// tRPC query resolves. Hardcoded so the landing page doesn't need to ship
// the full 765 KB catalog.json — picks were generated by the same
// "first item per category, take 5" algorithm Home used to run at runtime.
//
// Only the fields Home actually reads are populated; downstream code
// (Home.tsx) maps these into a richer CatalogItem with placeholders.
type PreviewItem = {
  id: string;
  name: string;
  organization: string;
  description: string;
  category: string;
  type: "grant" | "resource";
  country: string;
  eligibility: string;
  website: string;
  phone: string;
  email: string;
  amount: string;
  status: string;
};

export const catalogPreviewItems: PreviewItem[] = [
  {
    id: "item_0408",
    name: "321foundation",
    organization: "321foundation",
    description: "321foundation is a 501(c)(3) nonprofit that empowers individuals with Down syndrome through its iPad Program. Founded in 2014 by nine families in Bear, Delaware, the organization awards iPads with proven educational apps to individuals with intellectual disabilities to assist with communication, reading, and math skills.",
    category: "assistive_technology",
    type: "resource",
    country: "US",
    eligibility: "Ages 0-100; General Diagnosis; Location: USA",
    website: "https://321foundation.com",
    phone: "302-668-6177",
    email: "info@321foundation.com",
    amount: "Free service",
    status: "Active",
  },
  {
    id: "item_0297",
    name: "Access Grant",
    organization: "Adaptx",
    description: "Access Grant by Adaptx provides funding assistance for individuals with disabilities to obtain adaptive equipment and assistive technology.",
    category: "financial_assistance",
    type: "grant",
    country: "US",
    eligibility: "Ages 0-18; General Diagnosis, Financial Hardship; Location: USA",
    website: "https://www.adaptx.org",
    phone: "+90-542-224-8223",
    email: "brendan@adaptx.org",
    amount: "Varies",
    status: "Open",
  },
  {
    id: "item_0512",
    name: "Accessible Lodging Resource List (Tahoe Area, ADA Included)",
    organization: "Achieve Tahoe",
    description: "Anyone seeking accessible lodging near Achieve Tahoe; specific lodging booking handled through listed hotels/companies.",
    category: "housing",
    type: "grant",
    country: "US",
    eligibility: "Ages 0-100; General Diagnosis; Location: California, USA",
    website: "https://achievetahoe.org",
    phone: "(530) 581-4161",
    email: "info@achievetahoe.org",
    amount: "Free",
    status: "Open",
  },
  {
    id: "item_0573",
    name: "COTA",
    organization: "COTA",
    description: "Children's Organ Transplant Association — $10K challenge grant plus fundraising support for families.",
    category: "international",
    type: "resource",
    country: "US",
    eligibility: "Ages 0-100; Organ Transplant; Location: USA",
    website: "https://cota.org",
    phone: "800-366-2682",
    email: "cota@cota.org",
    amount: "Free service",
    status: "Active",
  },
  {
    id: "item_0001",
    name: "180 Medical Emotional Support and Resources",
    organization: "180 Medical",
    description: "Support, education, and product guidance for catheter and ostomy users seeking emotional adjustment resources.",
    category: "medical_treatment",
    type: "grant",
    country: "US",
    eligibility: "Ages 0-100; General Diagnosis; Location: USA",
    website: "https://www.180medical.com",
    phone: "877-688-2729",
    email: "info@180medical.com",
    amount: "Free",
    status: "Open",
  },
];
