#!/usr/bin/env bash
# Refresh self-hosted Google Fonts.
#
# Idempotent: re-running fetches the latest CSS from fonts.googleapis.com,
# re-downloads the WOFF2 subset files into client/public/fonts/, and
# rewrites url() references in client/src/fonts.css to point at the local
# files. If Google bumps a font version (v17 → v18) the new hashed
# filenames are downloaded automatically; old files become orphaned and
# can be cleaned up manually.
#
# Run after: bumping a font weight, adding a new family, or every few
# months as part of dependency hygiene.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
FONTS_DIR="${ROOT_DIR}/client/public/fonts"
CSS_OUT="${ROOT_DIR}/client/src/fonts.css"

# Same family/weight/axis specification the project uses. Keep in sync with
# any future @font-face additions.
FONT_QUERY="family=DM+Sans:ital,opsz,wght@0,9..40,400;0,9..40,500;0,9..40,600;0,9..40,700;1,9..40,400&family=Noto+Sans+Georgian:wght@400;500;600;700&display=swap"
FONT_URL="https://fonts.googleapis.com/css2?${FONT_QUERY}"
UA="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"

mkdir -p "${FONTS_DIR}"
TMP_CSS="$(mktemp)"
trap 'rm -f "${TMP_CSS}"' EXIT

echo "[fonts] Fetching CSS from Google…"
curl -sf -H "User-Agent: ${UA}" "${FONT_URL}" -o "${TMP_CSS}"

echo "[fonts] Downloading WOFF2 files…"
grep -oE 'https://fonts\.gstatic\.com/[^)]+\.woff2' "${TMP_CSS}" | sort -u | while IFS= read -r url; do
  fname="$(basename "${url}")"
  if [ ! -f "${FONTS_DIR}/${fname}" ]; then
    curl -sf -o "${FONTS_DIR}/${fname}" "${url}"
    echo "  ✓ ${fname}"
  else
    echo "  · ${fname} (already present)"
  fi
done

echo "[fonts] Rewriting CSS → ${CSS_OUT}"
{
  cat <<'EOF'
/*
 * Self-hosted Google Fonts (DM Sans + Noto Sans Georgian).
 *
 * Generated by scripts/refresh-fonts.sh — DO NOT edit by hand.
 * Re-run that script to refresh.
 */
EOF
  sed -E 's|https://fonts\.gstatic\.com/s/[^/]+/v[0-9]+/([^)]+\.woff2)|/fonts/\1|g' "${TMP_CSS}"
} > "${CSS_OUT}"

echo "[fonts] Done. Files: $(ls "${FONTS_DIR}" | wc -l), CSS lines: $(wc -l < "${CSS_OUT}")"
